var Example4_1 = [
             '<?xml version=\"1.0\" encoding=\"UTF-8\"?>',
             '',
             '<!-- ',
             '  http://wiki.ruleml.org/index.php/PSOA_RuleML#Single-tuple_psoa_term',
             '-->',
             '',
             '<!DOCTYPE Document [',
             '<!ENTITY psoa  \"http://www.w3.org/2011/psoa#\">',
             '<!ENTITY xs   \"http://www.w3.org/2001/XMLSchema#\">',
             '<!ENTITY rdf  \"http://www.w3.org/1999/02/22-rdf-syntax-ns#\">',
             ']>',
             '',
             '<Document xmlns=\"&psoa;\">',
             '  <payload>',
             '    <Group>',
             '      <sentence>',
             '        <Atom>',
             '          <oid>',
             '            <Ind type="&psoa;iri">_o1</Ind>',
             '          </oid>',
             '          <op>',
             '            <Rel type="&xs;local">_p</Rel>',
             '          </op>',
             '          <args>',
             '            <Ind type="&psoa;iri">_a1</Ind>',
             '            <Ind type="&psoa;iri">_a2</Ind>',
             '          </args>',
             '        </Atom>',
             '      </sentence>',
             '    </Group>',
             '  </payload>',
             '</Document>'].join('\n');