//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.24 at 09:41:24 AM AST 
//


package org.ruleml.psoa.parser.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://psoa.ruleml.org/lang/spec#}PSOA"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "oid",
    "op",
    "tuple",
    "indterm",
    "slot"
})
@XmlRootElement(name = "Expr")
public class Expr {

    protected Oid oid;
    @XmlElement(required = true)
    protected Op op;
    @XmlElement(name = "Tuple")
    protected List<Tuple> tuple;
    @XmlElements({
        @XmlElement(name = "Ind", type = Ind.class),
        @XmlElement(name = "Rel", type = Rel.class),
        @XmlElement(name = "Var", type = Var.class),
        @XmlElement(name = "Expr", type = Expr.class),
        @XmlElement(name = "External", type = ExternalTERMType.class)
    })
    protected List<Object> indterm;
    protected List<SlotPSOAType> slot;

    /**
     * Gets the value of the oid property.
     * 
     * @return
     *     possible object is
     *     {@link Oid }
     *     
     */
    public Oid getOid() {
        return oid;
    }

    /**
     * Sets the value of the oid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Oid }
     *     
     */
    public void setOid(Oid value) {
        this.oid = value;
    }

    /**
     * Gets the value of the op property.
     * 
     * @return
     *     possible object is
     *     {@link Op }
     *     
     */
    public Op getOp() {
        return op;
    }

    /**
     * Sets the value of the op property.
     * 
     * @param value
     *     allowed object is
     *     {@link Op }
     *     
     */
    public void setOp(Op value) {
        this.op = value;
    }

    /**
     * Gets the value of the tuple property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tuple property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTuple().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tuple }
     * 
     * 
     */
    public List<Tuple> getTuple() {
        if (tuple == null) {
            tuple = new ArrayList<Tuple>();
        }
        return this.tuple;
    }

    /**
     * Gets the value of the indterm property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the indterm property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getINDTERM().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ind }
     * {@link Rel }
     * {@link Var }
     * {@link Expr }
     * {@link ExternalTERMType }
     * 
     * 
     */
    public List<Object> getINDTERM() {
        if (indterm == null) {
            indterm = new ArrayList<Object>();
        }
        return this.indterm;
    }

    /**
     * Gets the value of the slot property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the slot property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSlot().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SlotPSOAType }
     * 
     * 
     */
    public List<SlotPSOAType> getSlot() {
        if (slot == null) {
            slot = new ArrayList<SlotPSOAType>();
        }
        return this.slot;
    }

}
