//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.10 at 03:21:02 PM AST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/2011/psoa#", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.ruleml.psoa.parser.jaxb;
