//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.30 at 11:30:16 AM AST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://psoa.ruleml.org/lang/spec#", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.ruleml.psoa.parser.jaxb;
