//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.10 at 03:21:02 PM AST 
//


package org.ruleml.psoa.parser.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for slot-PSOA.type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="slot-PSOA.type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.w3.org/2011/psoa#}TERM"/>
 *         &lt;group ref="{http://www.w3.org/2011/psoa#}TERM"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ordered" type="{http://www.w3.org/2001/XMLSchema}string" fixed="yes" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "slot-PSOA.type", propOrder = {
    "content"
})
public class SlotPSOAType {

    @XmlElementRefs({
        @XmlElementRef(name = "Expr", namespace = "http://www.w3.org/2011/psoa#", type = Expr.class),
        @XmlElementRef(name = "Ind", namespace = "http://www.w3.org/2011/psoa#", type = Ind.class),
        @XmlElementRef(name = "External", namespace = "http://www.w3.org/2011/psoa#", type = JAXBElement.class),
        @XmlElementRef(name = "Rel", namespace = "http://www.w3.org/2011/psoa#", type = Rel.class),
        @XmlElementRef(name = "Var", namespace = "http://www.w3.org/2011/psoa#", type = Var.class)
    })
    protected List<Object> content;
    @XmlAttribute(name = "ordered")
    protected String ordered;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "Ind" is used by two different parts of a schema. See: 
     * line 270 of file:/home/sadnana/NetBeansProjects/JavaClassesFromPSOARuleMLSchema/src/main/resources/schemas/PSOACond.xsd
     * line 270 of file:/home/sadnana/NetBeansProjects/JavaClassesFromPSOARuleMLSchema/src/main/resources/schemas/PSOACond.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link ExternalTERMType }{@code >}
     * {@link Expr }
     * {@link Ind }
     * {@link Rel }
     * {@link Var }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the ordered property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrdered() {
        if (ordered == null) {
            return "yes";
        } else {
            return ordered;
        }
    }

    /**
     * Sets the value of the ordered property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrdered(String value) {
        this.ordered = value;
    }

}
