/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


var Example4_5 = ['<?xml version=\"1.0" encoding=\"UTF-8"?>',
'',
'<!-- ',
'    http://www.w3.org/2005/rules/wiki/Class_Membership',
'-->',
'',
'<!DOCTYPE Document [',
'<!ENTITY psoa  "http://psoa.ruleml.org/lang/spec#\">',
'<!ENTITY xs   "http://www.w3.org/2001/XMLSchema#\">',
'<!ENTITY rdf  "http://www.w3.org/1999/02/22-rdf-syntax-ns#\">',
']>',
'<Document xmlns="&psoa;">',
'  <payload>',
'    <Group>',
'      <sentence>',
'        <Forall>',
'          <declare>',
'            <Var>X</Var>',
'          </declare>',
'          <declare>',
'            <Var>Y</Var>',
'          </declare>',          
'          <formula>',
'            <Implies>',
'              <if>',
'                <And>',
'                  <formula>',
'                    <Atom>',                     
'                      <op>',
'                        <Rel type="&psoa;local">fam:isChildOf</Rel>',
'                      </op>',
'                      <Tuple>',
'                        <Var>X</Var>',
'                        <Var>Y</Var>',
'                      </Tuple>',
'                    </Atom>',
'                  </formula>',
'                  <formula>',
'                    <Atom>',
'                      <oid>',
'                        <Var>Y</Var>',
'                      </oid>',
'                      <op>',
'                        <Rel type="&psoa;local">fam:Male</Rel>',
'                      </op>',
'                    </Atom>',
'                  </formula>',
'                </And>',
'              </if>',
'              <then>',
'                <Atom>',
'                  <op>',
'                    <Rel type="&psoa;local">fam:isFatherOf</Rel>',
'                  </op>',
'                  <Tuple>',
'                    <Var>Y</Var>',
'                    <Var>X</Var>',
'                  </Tuple>',
'                </Atom>',
'              </then>',
'            </Implies>',
'          </formula>',
'        </Forall>',
'      </sentence>',
'      <sentence>',
'        <Atom>',
'          <op>',
'            <Rel type="&psoa;local">fam:isChildOf</Rel>',
'          </op>',
'          <Tuple>',
'            <Ind type="&psoa;local">fam:Adrian</Ind>',
'            <Ind type="&psoa;local">fam:Uwe</Ind>',
'          </Tuple>',
'        </Atom>',
'      </sentence>',
'      <sentence>',
'        <Atom>',
'          <oid>',
'            <Ind type="&psoa;local">fam:Adrian</Ind>',
'          </oid>',
'          <op>',
'            <Rel type="&psoa;local">fam:Male</Rel>',
'          </op>',
'        </Atom>',
'      </sentence>',
'      <sentence>',
'        <Atom>',
'          <oid>',
'            <Ind type="&psoa;local">fam:Uwe</Ind>',
'          </oid>',
'          <op>',
'            <Rel type="&psoa;local">fam:Male</Rel>',
'          </op>',
'        </Atom>',
'      </sentence>',
'    </Group>',
'  </payload>',
'</Document>'].join('\n');
