/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

var Example4_18 = ['<?xml version=\"1.0" encoding=\"UTF-8"?>',
'',
'<!-- ',
'    http://wiki.ruleml.org/index.php/PSOA_RuleML#Factorial_1',
'-->',
'',
'<!DOCTYPE Document [',
'<!ENTITY psoa  "http://psoa.ruleml.org/lang/spec#\">',
'<!ENTITY xs   "http://www.w3.org/2001/XMLSchema#\">',
'<!ENTITY rdf  "http://www.w3.org/1999/02/22-rdf-syntax-ns#\">',
']>',
'',
'<Document xmlns="&psoa;">',
'  <payload>',
'    <Group>',
'      <sentence>',
'        <Forall>',
'          <declare>',
'            <Var>x</Var>',
'          </declare>',
'          <declare>',
'            <Var>y</Var>',
'          </declare>',
'          <declare>',
'            <Var>fx</Var>',
'          </declare>',
'          <declare>',
'            <Var>fy</Var>',
'          </declare>',
'          <formula>',
'            <Implies>',
'              <if>',
'                <And>',
'                  <formula>                    ',
'                    <Atom>                    ',
'                      <op>',
'                        <Rel type="&psoa;local">factorial</Rel>',
'                      </op>',
'                      <Tuple>',
'                        <Var>x</Var>',
'                        <Var>fx</Var>',
'                      </Tuple>',
'                    </Atom>                    ',
'                  </formula>',
'                  <formula>                    ',
'                    <Atom>',
'                      <op>',
'                        <Rel type="&psoa;local">multiply</Rel>',
'                      </op>',
'                      <Tuple>',
'                        <Var>fx</Var>',
'                        <Var>y</Var>',
'				<Var>fy</Var>',
'                      </Tuple>',
'                    </Atom>',
'                  </formula>',
'                  <formula>                    ',
'                    <Atom>',
'                      <op>',
'                        <Rel type="&psoa;local">sum</Rel>',
'                      </op>',
'                      <Tuple>',
'                        <Var>x</Var>',
'                        <Var>1</Var>',
'				<Var>y</Var>',
'                      </Tuple>',
'                    </Atom>',
'                  </formula>',
'                </And>',
'              </if>',
'              <then>',
'                <Atom>',
'                  <op>',
'                    <Rel type="&psoa;local">factorial</Rel>',
'                  </op>',
'                  <Tuple>',
'                    <Var>y</Var>',
'                    <Var>fy</Var>',
'                  </Tuple>',
'                </Atom>',
'              </then>',
'            </Implies>',
'          </formula>',
'        </Forall>',
'      </sentence>',
'      <sentence>',
'        <Atom>',
'          <op>',
'            <Rel type="&psoa;local">factorial</Rel>',
'          </op>',
'          <Tuple>',
'            <Ind type="&psoa;local">0</Ind>',
'            <Ind type="&psoa;local">1</Ind>',
'          </Tuple>',
'        </Atom>',
'      </sentence>',
'      <sentence>',
'        <Atom>',
'          <op>',
'            <Rel type="&psoa;local">sum</Rel>',
'          </op>',
'          <Tuple>',
'            <Ind type="&psoa;local">0</Ind>',
'            <Ind type="&psoa;local">1</Ind>',
'            <Ind type="&psoa;local">1</Ind>',
'          </Tuple>',
'        </Atom>',
'      </sentence>',
'      <sentence>',
'        <Atom>',
'          <op>',
'            <Rel type="&psoa;local">multiply</Rel>',
'          </op>',
'          <Tuple>',
'            <Ind type="&psoa;local">1</Ind>',
'            <Ind type="&psoa;local">1</Ind>',
'            <Ind type="&psoa;local">1</Ind>',
'          </Tuple>',
'        </Atom>',
'      </sentence>',
'      <sentence>',
'        <Atom>',
'          <op>',
'            <Rel type="&psoa;local">sum</Rel>',
'          </op>',
'          <Tuple>',
'            <Ind type="&psoa;local">1</Ind>',
'            <Ind type="&psoa;local">1</Ind>',
'            <Ind type="&psoa;local">2</Ind>',
'          </Tuple>',
'        </Atom>',
'      </sentence>',
'      <sentence>',
'        <Atom>',
'          <op>',
'            <Rel type="&psoa;local">multiply</Rel>',
'          </op>',
'          <Tuple>',
'            <Ind type="&psoa;local">1</Ind>',
'            <Ind type="&psoa;local">2</Ind>',
'            <Ind type="&psoa;local">3</Ind>',
'          </Tuple>',
'        </Atom>',
'      </sentence>',
'      <sentence>',
'        <Atom>',
'          <op>',
'            <Rel type="&psoa;local">sum</Rel>',
'          </op>',
'          <Tuple>',
'            <Ind type="&psoa;local">2</Ind>',
'            <Ind type="&psoa;local">1</Ind>',
'            <Ind type="&psoa;local">3</Ind>',
'          </Tuple>',
'        </Atom>',
'      </sentence>',
'      <sentence>',
'        <Atom>',
'          <op>',
'            <Rel type="&psoa;local">multiply</Rel>',
'          </op>',
'          <Tuple>',
'            <Ind type="&psoa;local">2</Ind>',
'            <Ind type="&psoa;local">3</Ind>',
'            <Ind type="&psoa;local">6</Ind>',
'          </Tuple>',
'        </Atom>',
'      </sentence>',
'      <sentence>',
'        <Atom>',
'          <op>',
'            <Rel type="&psoa;local">sum</Rel>',
'          </op>',
'          <Tuple>',
'            <Ind type="&psoa;local">3</Ind>',
'            <Ind type="&psoa;local">1</Ind>',
'            <Ind type="&psoa;local">4</Ind>',
'          </Tuple>',
'        </Atom>',
'      </sentence>',
'      <sentence>',
'        <Atom>',
'          <op>',
'            <Rel type="&psoa;local">multiply</Rel>',
'          </op>',
'          <Tuple>',
'            <Ind type="&psoa;local">6</Ind>',
'            <Ind type="&psoa;local">4</Ind>',
'            <Ind type="&psoa;local">24</Ind>',
'          </Tuple>',
'        </Atom>',
'      </sentence>',
'    </Group>',
'  </payload>',
'</Document>'].join('\n');