/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


var Example4_20 = ['<?xml version=\"1.0" encoding=\"UTF-8"?>',
'',
'<!-- ',
'    http://wiki.ruleml.org/index.php/PSOA_RuleML#Factorial_3',
'-->',
'',
'<!DOCTYPE Document [',
'<!ENTITY psoa  "http://psoa.ruleml.org/lang/spec#\">',
'<!ENTITY xs   "http://www.w3.org/2001/XMLSchema#\">',
'<!ENTITY rdf  "http://www.w3.org/1999/02/22-rdf-syntax-ns#\">',
']>',
'',
'<Document xmlns="&psoa;">',
'  <payload>',
'    <Group>',
'      <sentence>',
'        <Atom>',
'          <op>',
'            <Rel type="&psoa;local">factorial</Rel>',
'          </op>',
'          <Tuple>',
'            <Ind type="&xs;integer">0</Ind>',
'            <Ind type="&xs;integer">1</Ind>',
'          </Tuple>',
'        </Atom>',
'      </sentence>',
'      <sentence>',
'        <Forall>',
'          <declare>',
'            <Var>N</Var>',
'          </declare>',
'          <declare>',
'            <Var>F</Var>',
'          </declare>',
'          <declare>',
'            <Var>N1</Var>',
'          </declare>',
'          <declare>',
'            <Var>F1</Var>',
'          </declare>',
'          <formula>',
'            <Implies>',
'              <if>',
'                <And>',
'                  <formula>                    ',
'                    <External>',
'                     <content>',
'                      <Atom>',
'                        <op>',
'                          <Fun type="&psoa;local">pred:numeric-greater-than</Fun>',
'                        </op>',
'                        <Tuple>',
'                          <Var>N</Var>',
'                          <Ind type="&xs;integer">0</Ind>',
'                        </Tuple>',
'                      </Atom>',
'                     </content>',
'                    </External>',
'                  </formula>',
'                  <formula>                    ',
'                    <Equal>',
'                      <left>                        ',
'                        <Var>N1</Var>                      ',
'                      </left>',
'                      <right>',
'                        <External>',
'                          <content>',
'                            <Expr>',
'                              <op>',
'                                <Fun type="&psoa;local">func:numeric-subtract</Fun>',
'                              </op>',
'                              <Tuple>',
'                                <Var>N</Var>',
'                                <Ind type="&xs;integer">0</Ind>',
'                              </Tuple>',
'                            </Expr>',
'                          </content>',
'                        </External>',
'                      </right>',
'                    </Equal>',
'                  </formula>',
'                  <formula>                    ',
'                    <Equal>',
'                      <left>                        ',
'                        <Var>F</Var>                      ',
'                      </left>',
'                      <right>',
'                        <External>',
'                          <content>',
'                            <Expr>',
'                              <op>',
'                                <Fun type="&psoa;local">func:numeric-multiply</Fun>',
'                              </op>',
'                              <Tuple>',
'                                <Var>N</Var>',
'                                <Var>F1</Var>',
'                              </Tuple>',
'                            </Expr>',
'                          </content>',
'                        </External>',
'                      </right>',
'                    </Equal>',
'                  </formula>',
'                  <formula>                    ',
'                    <Atom>',
'                      <op>',
'                        <Rel type="&psoa;local">factorial</Rel>',
'                      </op>',
'                      <Tuple>',
'                        <Var>N1</Var>',
'                        <Var>F1</Var>',
'                      </Tuple>',
'                    </Atom>',
'                  </formula>',
'                </And>',
'              </if>',
'              <then>',
'                <Atom>',
'                  <op>',
'                    <Rel type="&psoa;local">factorial</Rel>',
'                  </op>',
'                  <Tuple>',
'                    <Var>N</Var>',
'                    <Var>F</Var>',
'                  </Tuple>',
'                </Atom>',
'              </then>',
'            </Implies>',
'          </formula>',
'        </Forall>',
'      </sentence>',
'    </Group>',
'  </payload>',
'</Document>'].join('\n');