var Example4_7= [
             '<?xml version=\"1.0\" encoding=\"UTF-8\"?>',
             '',
             '<!-- ',
             '  http://wiki.ruleml.org/index.php/PSOA_RuleML#Family_.28Variation.29',
             '-->',
             '',
             '<!DOCTYPE Document [',
             '<!ENTITY psoa  \"http://www.w3.org/2011/psoa#\">',
             '<!ENTITY xs   \"http://www.w3.org/2001/XMLSchema#\">',
             '<!ENTITY rdf  \"http://www.w3.org/1999/02/22-rdf-syntax-ns#\">',
             ']>',
             '',
             '<Document xmlns=\"&psoa;\">',
'  <payload>',
'    <Group>',
'      <sentence>',
'        <Forall>',
'          <declare>',
'            <Var>Hu</Var>',
'          </declare>',
'          <declare>',
'            <Var>Wi</Var>',
'          </declare>',
'          <formula>',
'            <Implies>',
'              <if>',
'                <Exists>',
'                  <declare>',
'                    <Var>obj2</Var>',
'                  </declare>',
'                  <formula>',
'                    <Atom>',
'                      <oid>',
'                        <Var>obj2</Var>',
'                      </oid>',
'                      <op>',
'                        <Rel type=\"&psoa;local\">_married</Rel>',
'                      </op>',
'                      <args>',
'                        <Var>Hu</Var>',
'                        <Var>Wi</Var>',
'                      </args>',
'                    </Atom>',
'                  </formula>',
'                </Exists>',
'              </if>',
'              <then>',
'                <Exists>',
'                  <declare>',
'                    <Var>obj1</Var>',
'                  </declare>',
'                  <formula>',
'                    <Atom>',
'                      <oid>',
'                        <Var>obj1</Var>',
'                      </oid>',
'                      <op>',
'                        <Rel type=\"&psoa;local\">_family</Rel>',
'                      </op>',
'                      <slot>',
'                        <Ind type=\"&psoa;local\">_husb</Ind>',
'                        <Var>Hu</Var>',
'                      </slot>',
'                      <slot>',
'                        <Ind type=\"&psoa;local\">_wife</Ind>',
'                        <Var>Wi</Var>',
'                      </slot>',
'                    </Atom>',
'                  </formula>',
'                </Exists>',
'              </then>',
'            </Implies>',
'          </formula>',
'        </Forall>',
'      </sentence>',
'      <sentence>',
'        <Forall>',
'          <declare>',
'            <Var>Hu</Var>',
'          </declare>',
'          <declare>',
'            <Var>Wi</Var>',
'          </declare>',
'          <declare>',
'            <Var>Ch</Var>',
'          </declare>',
'          <declare>',
'            <Var>o</Var>',
'          </declare>',
'          <formula>',
'            <Implies>',
'              <if>',
'                <And>',
'                  <formula>',
'                    <Atom>',
'                      <oid>',
'                        <Var>o</Var>',
'                      </oid>',
'                      <op>',
'                        <Rel type=\"&psoa;local\">_family</Rel>',
'                      </op>',
'                      <slot>',
'                        <Ind type=\"&psoa;local\">_husb</Ind>',
'                        <Var>Hu</Var>',
'                      </slot>',
'                      <slot>',
'                        <Ind type=\"&psoa;local\">_wife</Ind>',
'                        <Var>Wi</Var>',
'                      </slot>',
'                    </Atom>',
'                  </formula>',
'                  <formula>',
'                    <Exists>',
'                      <declare>',
'                        <Var>obj3</Var>',
'                      </declare>',
'                      <formula>',
'                        <Atom>',
'                          <oid>',
'                            <Var>obj3</Var>',
'                          </oid>',
'                          <op>',
'                            <Rel type=\"&psoa;local\">_kid</Rel>',
'                          </op>',
'                          <args>',
'                            <Var>Hu</Var>',
'                            <Var>Ch</Var>',
'                          </args>',
'                        </Atom>',
'                      </formula>',
'                    </Exists>',
'                  </formula>',
'                </And>',
'              </if>',
'              <then>',
'                <Atom>',
'                  <oid>',
'                    <Var>o</Var>',
'                  </oid>',
'                  <op>',
'                    <Rel type=\"&psoa;local\">_family</Rel>',
'                  </op>',
'                  <slot>',
'                    <Ind type=\"&psoa;local\">_child</Ind>',
'                    <Var>Ch</Var>',
'                  </slot>',
'                </Atom>',
'              </then>',
'            </Implies>',
'          </formula>',
'        </Forall>',
'      </sentence>',
'      <sentence>',
'        <Forall>',
'          <declare>',
'            <Var>Hu</Var>',
'          </declare>',
'          <declare>',
'            <Var>Wi</Var>',
'          </declare>',
'          <declare>',
'            <Var>Ch</Var>',
'          </declare>',
'          <declare>',
'            <Var>o</Var>',
'          </declare>',
'          <formula>',
'            <Implies>',
'              <if>',
'                <And>',
'                  <formula>',
'                    <Atom>',
'                      <oid>',
'                        <Var>o</Var>',
'                      </oid>',
'                      <op>',
'                        <Rel type=\"&psoa;local\">_family</Rel>',
'                      </op>',
'                      <slot>',
'                        <Ind type=\"&psoa;local\">_husb</Ind>',
'                        <Var>Hu</Var>',
'                      </slot>',
'                      <slot>',
'                        <Ind type=\"&psoa;local\">_wife</Ind>',
'                        <Var>Wi</Var>',
'                      </slot>',
'                    </Atom>',
'                  </formula>',
'                  <formula>',
'                    <Exists>',
'                      <declare>',
'                        <Var>obj4</Var>',
'                      </declare>',
'                      <formula>',
'                        <Atom>',
'                          <oid>',
'                            <Var>obj4</Var>',
'                          </oid>',
'                          <op>',
'                            <Rel type=\"&psoa;local\">_kid</Rel>',
'                          </op>',
'                          <args>',
'                            <Var>Wi</Var>',
'                            <Var>Ch</Var>',
'                          </args>',
'                        </Atom>',
'                      </formula>',
'                    </Exists>',
'                  </formula>',
'                </And>',
'              </if>',
'              <then>',
'                <Atom>',
'                  <oid>',
'                    <Var>o</Var>',
'                  </oid>',
'                  <op>',
'                    <Rel type=\"&psoa;local\">_family</Rel>',
'                  </op>',
'                  <slot>',
'                    <Ind type=\"&psoa;local\">_child</Ind>',
'                    <Var>Ch</Var>',
'                  </slot>',
'                </Atom>',
'              </then>',
'            </Implies>',
'          </formula>',
'        </Forall>',
'      </sentence>',
'      <sentence>',
'        <Atom>',
'          <oid>',
'            <Ind type=\"&psoa;local\">_m1</Ind>',
'          </oid>',
'          <op>',
'            <Rel type=\"&psoa;local\">_married</Rel>',
'          </op>',
'          <args>',
'            <Ind type=\"&psoa;local\">_Joe</Ind>',
'            <Ind type=\"&psoa;local\">_Sue</Ind>',
'          </args>',
'        </Atom>',
'      </sentence>',
'      <sentence>',
'        <Atom>',
'          <oid>',
'            <Ind type=\"&psoa;local\">_k1</Ind>',
'          </oid>',
'          <op>',
'            <Rel type=\"&psoa;local\">_kid</Rel>',
'          </op>',
'          <args>',
'            <Ind type=\"&psoa;local\">_Sue</Ind>',
'            <Ind type=\"&psoa;local\">_Pete</Ind>',
'          </args>',
'        </Atom>',
'      </sentence>',
'      <sentence>',
'        <Atom>',
'          <oid>',
'            <Ind type=\"&psoa;local\">_k2</Ind>',
'          </oid>',
'          <op>',
'            <Rel type=\"&psoa;local\">_kid</Rel>',
'          </op>',
'          <args>',
'            <Ind type=\"&psoa;local\">_Joe</Ind>',
'            <Ind type=\"&psoa;local\">_Tom</Ind>',
'          </args>',
'        </Atom>',
'      </sentence>',
'    </Group>',
'  </payload>',
'</Document>'].join('\n');