var Example4_22 = [
             '<?xml version=\"1.0\" encoding=\"UTF-8\"?>',
             '',
             '<!-- ',
             '  http://wiki.ruleml.org/index.php/PSOA_RuleML#Function_2_.28TBD.29',
             '-->',
             '',
             '<!DOCTYPE Document [',
             '<!ENTITY psoa  \"http://psoa.ruleml.org/lang/spec#\">',
             '<!ENTITY xs   \"http://www.w3.org/2001/XMLSchema#\">',
             '<!ENTITY rdf  \"http://www.w3.org/1999/02/22-rdf-syntax-ns#\">',
             ']>',
             '',
             '<Document xmlns=\"&psoa;\">',
'  <payload>',
'    <Group>',
'      <sentence>',
'        <Forall>',
'          <declare>',
'            <Var>x</Var>',
'          </declare>',
'          <declare>',
'            <Var>y</Var>',
'          </declare>',
'          <formula>',          
'                <Equal>',
'                  <left>',     
'                   <Expr>',           
'                    <op>',
'                      <Fun type="&psoa;local">f</Fun>',
'                    </op>',
'                    <Tuple>',
'                      <Var>x</Var>',
'                      <Var>y</Var>',
'	            </Tuple>',
'                   </Expr>',
'                  </left>',
'                  <right>',
'                    <External>',
'                     <content>',
'                      <Expr>',
'                        <op>',
'                          <Fun type="&psoa;local">func:numeric-subtract</Fun>',
'                        </op>',
'                        <Tuple>',
'                          <Var>x</Var>',
'                          <Var>y</Var>',
'                        </Tuple>',
'                      </Expr>',
'                     </content>',
'                    </External>',
'                  </right>',
'                </Equal>',                            
'         </formula>',
'       </Forall>',
'      </sentence>',
'    </Group>',
'  </payload>',
'</Document>'].join('\n');