var Example4_15 = [
             '<?xml version=\"1.0\" encoding=\"UTF-8\"?>',
             '',
             '<!-- ',
             '  http://wiki.ruleml.org/index.php/PSOA_RuleML#Inheritance',
             '-->',
             '',
             '<!DOCTYPE Document [',
             '<!ENTITY psoa  \"http://www.w3.org/2011/psoa#\">',
             '<!ENTITY xs   \"http://www.w3.org/2001/XMLSchema#\">',
             '<!ENTITY rdf  \"http://www.w3.org/1999/02/22-rdf-syntax-ns#\">',
             ']>',
             '',
             '<Document xmlns=\"&psoa;\">',
'  <payload>',
'    <Group>',
'      <sentence>',
'        <Atom xmlns=\"&psoa;\">',
'          <oid>',
'            <Ind type=\"&psoa;local\">_o1</Ind>',
'          </oid>',
'          <op>',
'            <Rel type=\"&psoa;local\">_c1</Rel>',
'          </op>',
'          <args>',
'            <Ind type=\"&psoa;local\">_a1</Ind>',
'            <Ind type=\"&psoa;local\">_a2</Ind>',
'          </args>',
'        </Atom>',
'      </sentence>',
'      <sentence>',
'        <Atom xmlns=\"&psoa;\">',
'          <oid>',
'            <Ind type=\"&psoa;local\">_o2</Ind>',
'          </oid>',
'          <op>',
'            <Rel type=\"&psoa;local\">_c1</Rel>',
'          </op>',
'          <slot>',
'            <Ind type=\"&psoa;local\">_p</Ind>',
'            <Ind type=\"&psoa;local\">_v</Ind>',
'          </slot>',
'        </Atom>',
'      </sentence>',
'      <sentence>',
'        <Subclass>',
'          <sub>',
'            <Ind type=\"&psoa;local\">_c1</Ind>',
'          </sub>',
'          <super>',
'            <Ind type=\"&psoa;local\">_c2</Ind>',
'          </super>',
'        </Subclass>',
'      </sentence>',
'    </Group>',
'  </payload>',
'</Document>'].join('\n');