var Example4_4 = [
             '<?xml version=\"1.0\" encoding=\"UTF-8\"?>',
             '',
             '<!-- ',
             '  http://wiki.ruleml.org/index.php/PSOA_RuleML#Psoa_terms_with_slots_and_tuples',
             '-->',
             '',
             '<!DOCTYPE Document [',
             '<!ENTITY psoa  \"http://psoa.ruleml.org/lang/spec#\">',
             '<!ENTITY xs   \"http://www.w3.org/2001/XMLSchema#\">',
             '<!ENTITY rdf  \"http://www.w3.org/1999/02/22-rdf-syntax-ns#\">',
             ']>',
             '',
             '<Document xmlns=\"&psoa;\">',
'  <payload>',
'    <Group>',
'      <sentence>',
'        <Atom xmlns=\"&psoa;\">',
'          <oid>',
'            <Ind type=\"&psoa;local\">f1</Ind>',
'          </oid>',
'          <op>',
'            <Rel type=\"&psoa;local\">family</Rel>',
'          </op>',
// implicit Tuple '          <Tuple>',
'          <Ind type=\"&psoa;local\">John</Ind>',
'          <Ind type=\"&psoa;local\">Mary</Ind>',
// implicit Tuple '          </Tuple>',
'          <slot>',
'            <Ind type=\"&psoa;local\">child</Ind>',
'            <Ind type=\"&psoa;local\">Tom</Ind>',
'          </slot>',
'        </Atom>',
'      </sentence>',
'      <sentence>',
'        <Atom xmlns=\"&psoa;\">',
'          <oid>',
'            <Ind type=\"&psoa;local\">f2</Ind>',
'          </oid>',
'          <op>',
'            <Rel type=\"&psoa;local\">family</Rel>',
'          </op>',
'          <Tuple>',
'            <Ind type=\"&psoa;local\">Tom</Ind>',
'            <Ind type=\"&psoa;local\">Jane</Ind>',
'          </Tuple>',
'          <slot>',
'            <Ind type=\"&psoa;local\">income</Ind>',
'            <Ind type=\"&xs;integer\">100000</Ind>',
'          </slot>',
'        </Atom>',
'      </sentence>',
'      <sentence>',
'        <Atom xmlns=\"&psoa;\">',
'          <oid>',
'            <Ind type=\"&psoa;local\">f3</Ind>',
'          </oid>',
'          <op>',
'            <Rel type=\"&psoa;local\">family</Rel>',
'          </op>',
'          <Tuple>',
'            <Ind type=\"&psoa;local\">Mike</Ind>',
'            <Ind type=\"&psoa;local\">Jessie</Ind>',
'          </Tuple>',
'          <Tuple>',
'            <Ind type=\"&xs;integer\">1951</Ind>',
'          </Tuple>',
'          <slot>',
'            <Ind type=\"&psoa;local\">child</Ind>',
'            <Ind type=\"&psoa;local\">Fred</Ind>',
'          </slot>',
'          <slot>',
'            <Ind type=\"&psoa;local\">child</Ind>',
'            <Ind type=\"&psoa;local\">Jane</Ind>',
'          </slot>',
'        </Atom>',
'      </sentence>',
'      <sentence>',
'        <Atom xmlns=\"&psoa;\">',
'          <oid>',
'            <Ind type=\"&psoa;local\">Jane</Ind>',
'          </oid>',
'          <op>',
'            <Rel type=\"&psoa;local\">Person</Rel>',
'          </op>',
'          <Tuple>',
'            <Ind type=\"&psoa;local\">female</Ind>',
'          </Tuple>',
'          <Tuple>',
'            <Ind type=\"&psoa;local\">bcs</Ind>',
'            <Ind type=\"&psoa;local\">mcs</Ind>',
'            <Ind type=\"&psoa;local\">phd</Ind>',
'          </Tuple>',
'          <slot>',
'            <Ind type=\"&psoa;local\">job</Ind>',
'            <Ind type=\"&psoa;local\">engineer</Ind>',
'          </slot>',
'        </Atom>',
'      </sentence>',
'    </Group>',
'  </payload>',
'</Document>'].join('\n');