/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

var Example4_14 = ['<?xml version=\"1.0" encoding=\"UTF-8"?>',
'',
'<!-- ',
'    http://wiki.ruleml.org/index.php/PSOA_RuleML#Recursion',
'-->',
'',
'<!DOCTYPE Document [',
'<!ENTITY psoa  "http://psoa.ruleml.org/lang/spec#\">',
'<!ENTITY xs   "http://www.w3.org/2001/XMLSchema#\">',
'<!ENTITY rdf  "http://www.w3.org/1999/02/22-rdf-syntax-ns#\">',
']>',
'',
'<Document xmlns="&psoa;">',
'  <payload>',
'    <Group>',
'      <sentence>',
'        <Forall>',
'          <declare>',
'            <Var>anc</Var>',
'          </declare>',
'          <declare>',
'            <Var>par</Var>',
'          </declare>',
'          <declare>',
'            <Var>des</Var>',
'          </declare>',
'          <formula>',
'            <Implies>',
'              <if>',
'                <And>',
'                  <formula>                    ',
'                    <Atom>                    ',
'                      <op>',
'                        <Rel type="&psoa;local">isChildOf</Rel>',
'                      </op>',
'                      <Tuple>',
'                        <Var>des</Var>',
'                        <Var>par</Var>',
'                      </Tuple>',
'                    </Atom>                    ',
'                  </formula>',
'                  <formula>                    ',
'                    <Atom>',
'                      <op>',
'                        <Rel type="&psoa;local">isDescendentOf</Rel>',
'                      </op>',
'                      <Tuple>',
'                        <Var>par</Var>',
'                        <Var>anc</Var>',
'                      </Tuple>',
'                    </Atom>',
'                  </formula>',
'                </And>',
'              </if>',
'              <then>',
'                <Atom>',
'                  <op>',
'                    <Rel type="&psoa;local">isDescendentOf</Rel>',
'                  </op>',
'                  <Tuple>',
'                    <Var>des</Var>',
'                    <Var>anc</Var>',
'                  </Tuple>',
'                </Atom>',
'              </then>',
'            </Implies>',
'          </formula>',
'        </Forall>',
'      </sentence>',
'      <sentence>',
'        <Forall>',
'          <declare>',
'            <Var>Hu</Var>',
'          </declare>',
'          <declare>',
'            <Var>Wi</Var>',
'          </declare>',
'          <formula>',
'            <Implies>',
'              <if>',
'                <Atom>                    ',
'                  <op>',
'                    <Rel type="&psoa;local">isChildOf</Rel>',
'                  </op>',
'                  <Tuple>',
'                    <Var>ch</Var>',
'                    <Var>par</Var>',
'                  </Tuple>',
'                </Atom>                    ',
'              </if>',
'              <then>',
'                <Atom>',
'                  <op>',
'                    <Rel type="&psoa;local">isDescendentOf</Rel>',
'                  </op>',
'                  <Tuple>',
'                    <Var>ch</Var>',
'                    <Var>par</Var>',
'                  </Tuple>',
'                </Atom>',
'              </then>',
'            </Implies>',
'          </formula>',
'        </Forall>',
'      </sentence>',
'      <sentence>',
'        <Atom>',
'          <op>',
'            <Rel type="&psoa;local">isChildOf</Rel>',
'          </op>',
'          <Tuple>',
'            <Ind type="&psoa;local">Pete</Ind>',
'            <Ind type="&psoa;local">Sue</Ind>',
'          </Tuple>',
'        </Atom>',
'      </sentence>',
'      <sentence>',
'        <Atom>',
'          <op>',
'            <Rel type="&psoa;local">isChildOf</Rel>',
'          </op>',
'          <Tuple>',
'            <Ind type="&psoa;local">Sue</Ind>',
'            <Ind type="&psoa;local">John</Ind>',
'          </Tuple>',
'        </Atom>',
'      </sentence>',
'      <sentence>',
'        <Atom>',
'          <op>',
'            <Rel type="&psoa;local">isChildOf</Rel>',
'          </op>',
'          <Tuple>',
'            <Ind type="&psoa;local">John</Ind>',
'            <Ind type="&psoa;local">Tom</Ind>',
'          </Tuple>',
'        </Atom>',
'      </sentence>',
'      <sentence>',
'        <Atom>',
'          <oid>',
'            <Ind type="&psoa;local">Pete</Ind>',
'          </oid>',
'          <op>',
'            <Rel type="&psoa;local">Person</Rel>',
'          </op>',
'          <slot>',
'            <Ind type="&psoa;local">sex</Ind>',
'            <Ind type="&psoa;local">Male</Ind>',
'          </slot>',
'          <slot>',
'            <Ind type="&psoa;local">age</Ind>',
'            <Ind type="&xs;integer">24</Ind>',
'          </slot>',
'        </Atom>',
'      </sentence>',
'      <sentence>',
'        <Atom>',
'          <oid>',
'            <Ind type="&psoa;local">Sue</Ind>',
'          </oid>',
'          <op>',
'            <Rel type="&psoa;local">Person</Rel>',
'          </op>',
'          <slot>',
'            <Ind type="&psoa;local">sex</Ind>',
'            <Ind type="&psoa;local">Female</Ind>',
'          </slot>',
'          <slot>',
'            <Ind type="&psoa;local">age</Ind>',
'            <Ind type="&xs;integer">47</Ind>',
'          </slot>',
'        </Atom>',
'      </sentence>',
'      <sentence>',
'        <Atom>',
'          <oid>',
'            <Ind type="&psoa;local">John</Ind>',
'          </oid>',
'          <op>',
'            <Rel type="&psoa;local">Person</Rel>',
'          </op>',
'          <slot>',
'            <Ind type="&psoa;local">sex</Ind>',
'            <Ind type="&psoa;local">Male</Ind>',
'          </slot>',
'          <slot>',
'            <Ind type="&psoa;local">age</Ind>',
'            <Ind type="&xs;integer">77</Ind>',
'          </slot>',
'        </Atom>',
'      </sentence>',
'    </Group>',
'  </payload>',
'</Document>'].join('\n');