var Example4_8 = [
             '<?xml version=\"1.0\" encoding=\"UTF-8\"?>',
             '',
             '<!-- ',
             '  http://wiki.ruleml.org/index.php/PSOA_RuleML#Rule_Test_-_Psoa_Terms',
             '-->',
             '',
             '<!DOCTYPE Document [',
             '<!ENTITY psoa  \"http://psoa.ruleml.org/lang/spec#\">',
             '<!ENTITY xs   \"http://www.w3.org/2001/XMLSchema#\">',
             '<!ENTITY rdf  \"http://www.w3.org/1999/02/22-rdf-syntax-ns#\">',
             ']>',
             '',
             '<Document xmlns=\"&psoa;\">',
'  <payload>',
'    <Group>',
'      <sentence>',
'        <Forall>',
'          <declare>',
'            <Var>X</Var>',
'          </declare>',
'          <declare>',
'            <Var>Y</Var>',
'          </declare>',
'          <declare>',
'            <Var>1</Var>',
'          </declare>',
'          <formula>',
'            <Implies>',
'              <if>',
'                <Atom>',
'                  <oid>',
'                    <Var>1</Var>',
'                  </oid>',
'                  <op>',
'                    <Rel type=\"&psoa;local\">R3</Rel>',
'                  </op>',
'                  <args>',
'                    <Var>X</Var>',
'                    <Var>Y</Var>',
'                  </args>',
'                  <slot>',
'                    <Ind type=\"&psoa;local\">p2</Ind>',
'                    <Ind type=\"&psoa;local\">v2</Ind>',
'                  </slot>',
'                </Atom>',
'              </if>',
'              <then>',
'                <Atom>',
'                  <oid>',
'                    <Var>1</Var>',
'                  </oid>',
'                  <op>',
'                    <Rel type=\"&psoa;local\">R4</Rel>',
'                  </op>',
'                  <args>',
'                    <Var>X</Var>',
'                    <Var>Y</Var>',
'                  </args>',
'                </Atom>',
'              </then>',
'            </Implies>',
'          </formula>',
'        </Forall>',
'      </sentence>',
'      <sentence>',
'        <Forall>',
'          <declare>',
'            <Var>X</Var>',
'          </declare>',
'          <declare>',
'            <Var>Y</Var>',
'          </declare>',
'          <declare>',
'            <Var>1</Var>',
'          </declare>',
'          <formula>',
'            <Implies>',
'              <if>',
'                <And>',
'                  <formula>',
'                    <Atom>',
'                      <oid>',
'                        <Var>X</Var>',
'                      </oid>',
'                      <op>',
'                        <Rel type=\"&psoa;local\">C2</Rel>',
'                      </op>',
'                      <slot>',
'                        <Ind type=\"&psoa;local\">p3</Ind>',
'                        <Ind type=\"&psoa;local\">v3</Ind>',
'                      </slot>',
'                    </Atom>',
'                  </formula>',
'                  <formula>',
'                    <Atom>',
'                      <oid>',
'                        <Var>1</Var>',
'                      </oid>',
'                      <op>',
'                        <Rel type=\"&psoa;local\">R2</Rel>',
'                      </op>',
'                      <args>',
'                        <Var>X</Var>',
'                        <Var>Y</Var>',
'                      </args>',
'                    </Atom>',
'                  </formula>',
'                </And>',
'              </if>',
'              <then>',
'                <Atom>',
'                  <oid>',
'                    <Var>1</Var>',
'                  </oid>',
'                  <op>',
'                    <Rel type=\"&psoa;local\">R3</Rel>',
'                  </op>',
'                  <args>',
'                    <Var>X</Var>',
'                    <Var>Y</Var>',
'                  </args>',
'                </Atom>',
'              </then>',
'            </Implies>',
'          </formula>',
'        </Forall>',
'      </sentence>',
'      <sentence>',
'        <Forall>',
'          <declare>',
'            <Var>X</Var>',
'          </declare>',
'          <declare>',
'            <Var>Y</Var>',
'          </declare>',
'          <declare>',
'            <Var>1</Var>',
'          </declare>',
'          <formula>',
'            <Implies>',
'              <if>',
'                <Atom>',
'                  <oid>',
'                    <Var>1</Var>',
'                  </oid>',
'                  <op>',
'                    <Rel type=\"&psoa;local\">R1</Rel>',
'                  </op>',
'                  <args>',
'                    <Var>X</Var>',
'                    <Var>Y</Var>',
'                  </args>',
'                </Atom>',
'              </if>',
'              <then>',
'                <Atom>',
'                  <oid>',
'                    <Var>1</Var>',
'                  </oid>',
'                  <op>',
'                    <Rel type=\"&psoa;local\">R2</Rel>',
'                  </op>',
'                  <args>',
'                    <Var>X</Var>',
'                    <Var>Y</Var>',
'                  </args>',
'                  <slot>',
'                    <Ind type=\"&psoa;local\">p1</Ind>',
'                    <Ind type=\"&psoa;local\">v1</Ind>',
'                  </slot>',
'                  <slot>',
'                    <Ind type=\"&psoa;local\">p2</Ind>',
'                    <Ind type=\"&psoa;local\">v2</Ind>',
'                  </slot>',
'                </Atom>',
'              </then>',
'            </Implies>',
'          </formula>',
'        </Forall>',
'      </sentence>',
'      <sentence>',
'        <Forall>',
'          <declare>',
'            <Var>1</Var>',
'          </declare>',
'          <formula>',
'            <Implies>',
'              <if>',
'                <Atom>',
'                  <oid>',
'                    <Var>1</Var>',
'                  </oid>',
'                  <op>',
'                    <Rel type=\"&psoa;local\">C1</Rel>',
'                  </op>',
'                </Atom>',
'              </if>',
'              <then>',
'                <Atom>',
'                  <oid>',
'                    <Var>1</Var>',
'                  </oid>',
'                  <op>',
'                    <Rel type=\"&psoa;local\">C2</Rel>',
'                  </op>',
'                </Atom>',
'              </then>',
'            </Implies>',
'          </formula>',
'        </Forall>',
'      </sentence>',
'      <sentence>',
'        <Atom>',
'          <oid>',
'            <Ind type=\"&psoa;local\">a1</Ind>',
'          </oid>',
'          <op>',
'            <Rel type=\"&psoa;local\">C1</Rel>',
'          </op>',
'        </Atom>',
'      </sentence>',
'      <sentence>',
'        <Atom>',
'          <oid>',
'            <Ind type=\"&psoa;local\">o1</Ind>',
'          </oid>',
'          <op>',
'            <Rel type=\"&psoa;local\">R1</Rel>',
'          </op>',
'          <args>',
'            <Ind type=\"&psoa;local\">a1</Ind>',
'            <Ind type=\"&psoa;local\">b1</Ind>',
'          </args>',
'        </Atom>',
'      </sentence>',
'      <sentence>',
'        <Atom>',
'          <oid>',
'            <Ind type=\"&psoa;local\">a2</Ind>',
'          </oid>',
'          <op>',
'            <Rel type=\"&psoa;local\">C1</Rel>',
'          </op>',
'          <slot>',
'            <Ind type=\"&psoa;local\">p3</Ind>',
'            <Ind type=\"&psoa;local\">v3</Ind>',
'          </slot>',
'          <slot>',
'            <Ind type=\"&psoa;local\">p4</Ind>',
'            <Ind type=\"&psoa;local\">v4</Ind>',
'          </slot>',
'        </Atom>',
'      </sentence>',
'      <sentence>',
'        <Atom>',
'          <oid>',
'            <Ind type=\"&psoa;local\">o2</Ind>',
'          </oid>',
'          <op>',
'            <Rel type=\"&psoa;local\">R1</Rel>',
'          </op>',
'          <args>',
'            <Ind type=\"&psoa;local\">a2</Ind>',
'            <Ind type=\"&psoa;local\">b2</Ind>',
'          </args>',
'        </Atom>',
'      </sentence>',
'      <sentence>',
'        <Atom>',
'          <oid>',
'            <Ind type=\"&psoa;local\">a3</Ind>',
'          </oid>',
'          <op>',
'            <Rel type=\"&psoa;local\">C1</Rel>',
'          </op>',
'        </Atom>',
'      </sentence>',
'      <sentence>',
'        <Atom>',
'          <oid>',
'            <Ind type=\"&psoa;local\">o3</Ind>',
'          </oid>',
'          <op>',
'            <Rel type=\"&psoa;local\">R1</Rel>',
'          </op>',
'          <args>',
'            <Ind type=\"&psoa;local\">a3</Ind>',
'            <Ind type=\"&psoa;local\">b3</Ind>',
'            <Ind type=\"&psoa;local\">c3</Ind>',
'          </args>',
'        </Atom>',
'      </sentence>',
'    </Group>',
'  </payload>',
'</Document>'].join('\n');